name = "lockness"
version = "0.1.0"
defaultTargets = ["Lockness", "lockness-sim"]
leanOptions = { warningAsError = true }

[[lean_lib]]
name = "Lockness"
globs = ["Lockness.*"]

[[lean_exe]]
name = "lockness-sim"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "8a178386ffc0f5fef0b77738bb5449d50efeea95"
